"""initial schema tenant keys reconcil

Revision ID: b38032f6388f
Revises: 
Create Date: 2026-08-24 06:24:16.314150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b38032f6388f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'idempotency_key', name='uq_idem_principal_key')
    )
    op.create_index(op.f('ix_idempotency_records_principal_id'), 'idempotency_records', ['principal_id'], unique=False)
    op.create_table('invocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('mandate_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('server', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invocation_principal_idempotency_key', 'invocations', ['principal_id', 'idempotency_key'], unique=False)
    op.create_index(op.f('ix_invocations_mandate_id'), 'invocations', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_invocations_principal_id'), 'invocations', ['principal_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('mandate_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('remaining_after', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_events_kind'), 'ledger_events', ['kind'], unique=False)
    op.create_index(op.f('ix_ledger_events_mandate_id'), 'ledger_events', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_principal_id'), 'ledger_events', ['principal_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_task_id'), 'ledger_events', ['task_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('mandate_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('reservation_id', sa.String(length=36), nullable=True),
    sa.Column('tool', sa.String(length=80), nullable=False),
    sa.Column('server', sa.String(length=80), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('pubkey_hex', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_agent_id'), 'receipts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_receipts_mandate_id'), 'receipts', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_receipts_principal_id'), 'receipts', ['principal_id'], unique=False)
    op.create_index(op.f('ix_receipts_task_id'), 'receipts', ['task_id'], unique=False)
    op.create_table('reconciliation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invocation_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('evidence_ref', sa.String(length=200), nullable=False),
    sa.Column('evidence_kind', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_events_invocation_id'), 'reconciliation_events', ['invocation_id'], unique=False)
    op.create_table('used_nonces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'nonce', name='uq_principal_nonce')
    )
    op.create_index(op.f('ix_used_nonces_principal_id'), 'used_nonces', ['principal_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix', name='uq_api_key_prefix')
    )
    op.create_index(op.f('ix_api_keys_account_id'), 'api_keys', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pubkey_hex', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principals_account_id'), 'principals', ['account_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_principal_id'), 'agents', ['principal_id'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('parent_mandate_id', sa.String(length=36), nullable=True),
    sa.Column('spend_limit_cents', sa.Integer(), nullable=False),
    sa.Column('remaining_cents', sa.Integer(), nullable=False),
    sa.Column('max_call_cents', sa.Integer(), nullable=False),
    sa.Column('max_calls', sa.Integer(), nullable=True),
    sa.Column('calls_used', sa.Integer(), nullable=False),
    sa.Column('tools_json', sa.Text(), nullable=True),
    sa.Column('servers_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_subagent_budget_cents', sa.Integer(), nullable=True),
    sa.Column('nonce', sa.String(length=80), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('pubkey_hex', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_call_cents >= 0', name='ck_mandate_max_call_nonneg'),
    sa.CheckConstraint('max_subagent_budget_cents IS NULL OR max_subagent_budget_cents >= 0', name='ck_mandate_subagent_nonneg'),
    sa.CheckConstraint('remaining_cents >= 0', name='ck_mandate_remaining_nonneg'),
    sa.CheckConstraint('spend_limit_cents >= 0', name='ck_mandate_spend_nonneg'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_mandate_id'], ['mandates.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce', name='uq_mandate_nonce')
    )
    op.create_index(op.f('ix_mandates_agent_id'), 'mandates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mandates_nonce'), 'mandates', ['nonce'], unique=False)
    op.create_index(op.f('ix_mandates_principal_id'), 'mandates', ['principal_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_principal_id'), 'tasks', ['principal_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('principal_id', sa.String(length=36), nullable=False),
    sa.Column('mandate_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('nonce', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name='ck_reservation_amount_nonneg'),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_mandate_id'), 'reservations', ['mandate_id'], unique=False)
    op.create_index(op.f('ix_reservations_principal_id'), 'reservations', ['principal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_principal_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_mandate_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_tasks_principal_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_mandates_principal_id'), table_name='mandates')
    op.drop_index(op.f('ix_mandates_nonce'), table_name='mandates')
    op.drop_index(op.f('ix_mandates_agent_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_agents_principal_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_principals_account_id'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_account_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_used_nonces_principal_id'), table_name='used_nonces')
    op.drop_table('used_nonces')
    op.drop_index(op.f('ix_reconciliation_events_invocation_id'), table_name='reconciliation_events')
    op.drop_table('reconciliation_events')
    op.drop_index(op.f('ix_receipts_task_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_principal_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_mandate_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_agent_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_ledger_events_task_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_principal_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_mandate_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_kind'), table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_invocations_principal_id'), table_name='invocations')
    op.drop_index(op.f('ix_invocations_mandate_id'), table_name='invocations')
    op.drop_index('ix_invocation_principal_idempotency_key', table_name='invocations')
    op.drop_table('invocations')
    op.drop_index(op.f('ix_idempotency_records_principal_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_table('billing_outbox')
    op.drop_table('accounts')
    # ### end Alembic commands ###
